### ISSUE TITLE
Change wifi from config settings

### ISSUE THREAD

**Issue by Btazbt** [mp-se/gravitymon#150]
It would be nice to be able change the wifi connection from the configuration page too.

**Comment by mp-se** [comment]
This has been raised before and its possible to do. 

But since there is not real security when reading the device configuration that would expose your wifi credentials to anyone that can access the device. That is the reason for not including them in the configuration page, now they are only exposed when accessing a private access point.

An option would be to allow the user to set the wifi password but not view it.

**Comment by Btazbt** [comment]
An option would be to allow the user to set the wifi ap/password but not view it.

This seems fine. I don't think there is any reason to see the current configuration. just a list of visible wifi sources and a place to select or type in the bame to use and an entry for the password.

**Comment by mp-se** [comment]
Good, I will add this to the next version. 

Add possibility to enter wifi configuration and set the password from the UI. 
Scan for current wifi networks and allow the user to select from a list. 
Current password should not be shown since there is no security on getting data from the device.

**Comment by mp-se** [comment]
Added to dev branch and will be part of 1.4 release
