### ISSUE TITLE
show the correct device.local name to connect to in initial setup

### ISSUE THREAD

**Issue by Josverl** [mp-se/gravitymon#45]
## Issue 
On initial setup I found that the IP address generated by the interface was incorrect ( 192.168.4.1
and it was quite hard to find either : 
- the mdns name (requires installation of mdns tools) 
- or the device IP address, 
  - apparently no host name is associated with the DHCP request 
  - as the DHCP lease is released quite quickly , the router does not show the client in the lease table 
- I ended up reading the serial debug to find the IP address 

## Expected behaviour: 
- the mdsn name to be `<devicename>.local `  as documented : https://mp-se.github.io/gravitymon/configuration.html
I assume that, in order to run multiple devices on the same network,  you have added a few characters to the mdns name to make it unique , which works quite well in my own projects,  however that only works if this device name is also shown to the end user doing the configuration.

## Proposed  fix :
- the used mdsns name to be shown and linked in the setup UX as [`http://<devicename>ABCDEF.local`](http://devicenameABCDEF.local)

**Comment by mp-se** [comment]
Dont really understand what the issue is. When doing the initial wifi setup the ip for the device is hardcoded to 192.168.4.1 which is also stated in the documentation. 

MDNS would not be active until it joins the network after WIFI setup. If you are using Windows you would need to install 3rd party tools for this support. 

You have a point regarding the MDNS name since I make this unique. I would be good to have this visible on the WIFI setup page.

**Comment by mp-se** [comment]
Added device name to wifi setup page
